#!/usr//bin/env Rscript
library(plumber)

hip_json <- function(){
  function(val, req, res, errorHandler){
    tryCatch({
      json <- jsonlite::toJSON(val,digits=NA,force=TRUE)

      res$setHeader("Content-Type", "application/json")
      res$body <- json

      return(res$toResponse())
    }, error=function(e){
      errorHandler(req, res, e)
    })
  }
}

addSerializer("hip_json",hip_json)

port <- 8010
r <- plumb("ismev.R")
r$run(port=port)
